# Generated by Django 3.1 on 2020-08-15 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Design Picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('engineer', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('designs', models.ManyToManyField(to='office.Design', verbose_name='Designs')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Location Picture')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.service')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Measurement',
                'verbose_name_plural': 'Request Measurements',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(blank=True, null=True, verbose_name='Reply')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['reply_message'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('sender', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sender Email')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Name')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Engineer Contacted')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['title'],
            },
        ),
    ]
