# Generated by Django 3.1 on 2020-10-20 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0003_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEngineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('message', models.TextField(blank=True, null=True, verbose_name='الرساله')),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الألكترونى الخاص بالمرسل')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المرسل')),
                ('engineer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المهندس')),
            ],
            options={
                'verbose_name': 'المرسل',
                'verbose_name_plural': 'المرسلات',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['title'], 'verbose_name': 'العمل ', 'verbose_name_plural': 'الأعمال '},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['reply_message'], 'verbose_name': 'الرد', 'verbose_name_plural': 'الردود'},
        ),
        migrations.AlterModelOptions(
            name='requestmeasurement',
            options={'ordering': ['user'], 'verbose_name': 'طلب مقايسه', 'verbose_name_plural': ' طلبات مقايسه'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'الخدمه', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['color'], 'verbose_name': 'استطلاع رأى', 'verbose_name_plural': 'استطلاعات الرأى'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['name'], 'verbose_name': 'العمل ', 'verbose_name_plural': 'الأعمال '},
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='designs',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='design_type',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.work', verbose_name='التصميمات'),
        ),
        migrations.AddField(
            model_name='survey',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.service', verbose_name='نوع الخدمه'),
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='الرساله'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='العميل', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='الأجابه'),
        ),
        migrations.AlterField(
            model_name='requestmeasurement',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='requestmeasurement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='requestmeasurement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.service', verbose_name='الخدمه'),
        ),
        migrations.AlterField(
            model_name='requestmeasurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='requestwork',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='requestwork',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم'),
        ),
        migrations.AlterField(
            model_name='requestwork',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة الموقع'),
        ),
        migrations.AlterField(
            model_name='requestwork',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اللون المفضل'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاهتمامات'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نبذه'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='work',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم'),
        ),
        migrations.DeleteModel(
            name='Design',
        ),
    ]
